AI_DECISION_QUERY = """

SELECT

    D.MACHINE_NAME,
    D.OEE,
    D.PROBLEM_TYPE,
    D.TOTAL_LOSS,

    R.POSSIBLE_CAUSE,
    R.CATEGORY,
    R.PROBABILITY,
    R.RECOMMENDED_ACTION

FROM AI_OPERATIONS.AI_RESULTS.AI_DECISION_ENGINE D

LEFT JOIN AI_OPERATIONS.AI_CONFIG.ROOT_CAUSE_LIBRARY R

ON D.PROBLEM_TYPE = R.PROBLEM_TYPE

QUALIFY ROW_NUMBER() OVER
(
    PARTITION BY D.MACHINE_NAME
    ORDER BY R.PROBABILITY DESC
) = 1

ORDER BY D.OEE ASC;

"""